/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#1a1c19",
        "primary-container": "#c8102e",
        "outline": "#906f6e",
        "primary-fixed-dim": "#ffb3b1",
        "on-primary": "#ffffff",
        "surface-container": "#eeeee9",
        "surface-container-highest": "#e3e3de",
        "inverse-on-surface": "#f1f1ec",
        "on-primary-fixed": "#410007",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#ffdda8",
        "inverse-primary": "#ffb3b1",
        "primary-fixed": "#ffdad8",
        "outline-variant": "#e5bdbb",
        "error": "#ba1a1a",
        "surface-container-high": "#e8e8e3",
        "on-secondary-fixed": "#001b3c",
        "error-container": "#ffdad6",
        "surface": "#fafaf5",
        "surface-tint": "#bf0229",
        "on-tertiary-fixed": "#271900",
        "surface-bright": "#fafaf5",
        "on-error-container": "#93000a",
        "secondary": "#3a5f94",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#92001c",
        "tertiary": "#664603",
        "secondary-fixed-dim": "#a7c8ff",
        "on-secondary-container": "#294f83",
        "secondary-container": "#9fc2fe",
        "tertiary-fixed": "#ffdeab",
        "primary": "#9e001f",
        "on-surface": "#1a1c19",
        "tertiary-container": "#815e1c",
        "on-surface-variant": "#5c403f",
        "surface-variant": "#e3e3de",
        "on-secondary-fixed-variant": "#1f477b",
        "on-tertiary-fixed-variant": "#5f4100",
        "surface-container-low": "#f4f4ef",
        "secondary-fixed": "#d5e3ff",
        "inverse-surface": "#2f312e",
        "surface-dim": "#dadad5",
        "on-primary-container": "#ffdad8",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#edbf74",
        "background": "#fafaf5",
        "on-error": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "custom-full": "0.75rem"
      },
      spacing: {
        "container-max": "1280px",
        "margin-mobile": "20px",
        "unit": "8px",
        "margin-desktop": "64px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-md": ["Source Serif 4"],
        "headline-lg": ["Source Serif 4"],
        "display-lg": ["Source Serif 4"],
        "body-md": ["Public Sans"],
        "label-sm": ["Public Sans"],
        "headline-lg-mobile": ["Source Serif 4"],
        "body-lg": ["Public Sans"],
        "label-lg": ["Public Sans"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "display-lg": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
